package aks.stocks;


import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;


import aks.database.*;
import aks.constants.*;


public class StockManager {

	public StockValue FetchValueFromWeb(Stock s, Calendar d, Integer Market) throws IOException{		
		StockValue sv = null;
		
		//Construct url to fetch stock data
		String qstring = "http://real-chart.finance.yahoo.com/table.csv?";
		
		if(Market == Constants.MARKET_BSE){
			qstring = qstring + "s="+s.getYahoocode()+".BO";}
		else{
			qstring = qstring + "s="+s.getYahoocode()+".NS";}
		
		qstring = qstring + "&a="+Integer.toString(d.get(Calendar.MONTH));
		qstring = qstring + "&b="+Integer.toString(d.get(Calendar.DAY_OF_MONTH));
		qstring = qstring + "&c="+Integer.toString(d.get(Calendar.YEAR));
		
		qstring = qstring + "&d="+Integer.toString(d.get(Calendar.MONTH));
		qstring = qstring + "&e="+Integer.toString(d.get(Calendar.DAY_OF_MONTH));
		qstring = qstring + "&f="+Integer.toString(d.get(Calendar.YEAR));
		
		qstring = qstring + "&g=d&ignore=.csv";
		
		System.out.println(qstring);
		//Fetch csv file		
		URL url = new URL(qstring );
		BufferedReader br = new BufferedReader(new InputStreamReader(url.openStream()));
		try{
		int linenumber =1;	
		String strTemp;
		while(null != (strTemp = br.readLine())){
			
			if(linenumber == 2){				
				sv = this.getStockValudFromCSVLine(strTemp);
				}
			linenumber = linenumber + 1; 
			System.out.println(strTemp);
			}
		}catch(Exception e){
			System.out.println("error occured" + e.getLocalizedMessage());
		}		
		return sv;		
	}
		
 	public ArrayList<StockValue> FetchValuesFromWeb(Stock s, Calendar d1, Calendar d2, Integer Market) throws IOException{
		StockValue sv = null;
		ArrayList<StockValue> arrStocsValue = new ArrayList<StockValue>(); 
		//Construct url to fetch stock data
		String qstring = "http://real-chart.finance.yahoo.com/table.csv?";
		
		if(Market == Constants.MARKET_BSE){
			qstring = qstring + "s="+s.getYahoocode()+".BO";}
		else{
			qstring = qstring + "s="+s.getYahoocode()+".NS";}
		
		qstring = qstring + "&a="+Integer.toString(d1.get(Calendar.MONTH));
		qstring = qstring + "&b="+Integer.toString(d1.get(Calendar.DAY_OF_MONTH));
		qstring = qstring + "&c="+Integer.toString(d1.get(Calendar.YEAR));
		
		qstring = qstring + "&d="+Integer.toString(d2.get(Calendar.MONTH));
		qstring = qstring + "&e="+Integer.toString(d2.get(Calendar.DAY_OF_MONTH));
		qstring = qstring + "&f="+Integer.toString(d2.get(Calendar.YEAR));
		
		qstring = qstring + "&g=d&ignore=.csv";
		
		//System.out.println(qstring);
		
		
		//Fetch csv file		
		URL url = new URL(qstring );
		BufferedReader br = new BufferedReader(new InputStreamReader(url.openStream()));
		
		try{
			Integer linenumber =1;	
			String strTemp;
			while(null != (strTemp = br.readLine())){				
				if(linenumber != 1){				
					sv = this.getStockValudFromCSVLine(strTemp);
					arrStocsValue.add(sv);
					}
				linenumber = linenumber + 1; 
				//System.out.println(strTemp);
				}
			}catch(Exception e){
				System.out.println("error occured" + e.getLocalizedMessage());
			}		
		
		return arrStocsValue;
	}
	
	public StockValue getStockValudFromCSVLine(String s) throws ParseException{
		StockValue sv = null;
		String[] vals;
		sv = new StockValue();
		
		vals = s.split(",");	
		//get date
		String dateStr = vals[0]; 
		DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd"); 
		Date dtStock = (Date)formatter.parse(dateStr); 
		Calendar calStock = Calendar.getInstance();
		calStock.setTime(dtStock);
		sv.setDt(calStock);
		
		sv.setOpen(Double.parseDouble(vals[1]));
		sv.setHigh(Double.parseDouble(vals[2]));
		sv.setLow(Double.parseDouble(vals[3]));
		sv.setClose(Double.parseDouble(vals[4]));
		sv.setVolume(Double.parseDouble(vals[5]));	
		sv.setAdjclose(Double.parseDouble(vals[6]));		
		return sv;		
		}
	
	public void populateStockData(Stock s, Calendar startdate, Calendar endDate, Integer market){
		
	
		
		
	}
	
	public ArrayList<Stock> getAllStocks() throws ClassNotFoundException, SQLException{
		
		ArrayList<Stock> stocklist = new ArrayList<Stock>();
		
		String sql;
		sql = 	"SELECT A.unid as stockunid, "+ 
				"A.name as stockname, "+ 
				"A.yahoocode as yahoocode, "+ 
				"A.bsecode as bsecode, "+
				"A.nsecode as nsecode, "+
				"B.name as sector, "+
				"B.category as sectorcategory "+
				"FROM stocks.tb_stocks A "+
				"join stocks.tb_sectors B "+
				"on A.fk_sectorid = B.unid "+
				"ORDER BY A.name";
		
		ResultSet rs;
		Database db = new Database();
		rs = db.executeSQL(sql);
		
		while(rs.next()){
			Stock s = new Stock();
			s.setStockname(rs.getString("stockname"));
			s.setBsecode(rs.getString("bsecode"));
			s.setNsecode(rs.getString("nsecode"));
			s.setYahoocode(rs.getString("yahoocode"));
			s.setSector(rs.getString("sector"));
			s.setSectorCategory(rs.getString("sectorcategory"));
			s.setUnid(rs.getInt("stockunid"));			
			stocklist.add(s);
		}		
		
		return stocklist;		
	}
	
	public Stock getStockObjectFromName(String stockname) throws SQLException, ClassNotFoundException{
	String sql = "";
	sql = "SELECT A.unid as stockunid, "+ 
			"A.name as stockname, "+ 
			"A.yahoocode as yahoocode, "+ 
			"A.bsecode as bsecode, "+
			"A.nsecode as nsecode, "+
			"B.name as sector, "+
			"B.category as sectorcategory "+
			"FROM stocks.tb_stocks A "+
			"join stocks.tb_sectors B "+
			"on A.fk_sectorid = B.unid "+
			"where A.name = '#STOCK_NAME#' ";
	
	sql = sql.replace("#STOCK_NAME#", stockname);
	Database db = new Database();
	ResultSet rs =  db.executeSQL(sql);
	rs.next();	
	
	Stock s = new Stock();
	s.setStockname(rs.getString("stockname"));
	s.setBsecode(rs.getString("bsecode"));
	s.setNsecode(rs.getString("nsecode"));
	s.setYahoocode(rs.getString("yahoocode"));
	s.setSector(rs.getString("sector"));
	s.setSectorCategory(rs.getString("sectorcategory"));
	s.setUnid(rs.getInt("stockunid"));
	
	return s;
	}
		
	public Stock getStockObjectFromUNID(String stockunid) throws SQLException, ClassNotFoundException{
		String sql = "";
		sql = "SELECT A.unid as stockunid, "+ 
				"A.name as stockname, "+ 
				"A.yahoocode as yahoocode, "+ 
				"A.bsecode as bsecode, "+
				"A.nsecode as nsecode, "+
				"B.name as sector, "+
				"B.category as sectorcategory "+
				"FROM stocks.tb_stocks A "+
				"join stocks.tb_sectors B "+
				"on A.fk_sectorid = B.unid "+
				"where A.unid = '#STOCK_UNID#' ";
		
		sql = sql.replace("#STOCK_UNID#", stockunid);
		Database db = new Database();
		ResultSet rs =  db.executeSQL(sql);
		rs.next();	
		
		Stock s = new Stock();
		s.setStockname(rs.getString("stockname"));
		s.setBsecode(rs.getString("bsecode"));
		s.setNsecode(rs.getString("nsecode"));
		s.setYahoocode(rs.getString("yahoocode"));
		s.setSector(rs.getString("sector"));
		s.setSectorCategory(rs.getString("sectorcategory"));
		s.setUnid(rs.getInt("stockunid"));
		
		return s;
		}
	
	public String getPattern(Stock s, Calendar d, int Market) throws IOException{
	
		Calendar d1,d2;
		
		double[] arrClose = new double[5];
		int counter;
		int arrSize;
		int loopCounter;
		ArrayList<StockValue> arrSV;
		d1 = d;
		d2 = Calendar.getInstance();
		d2.setTime(d1.getTime());
		d2.add(Calendar.DAY_OF_MONTH, -10);		
		System.out.println(d1.getTime() + " -> " + d2.getTime());
		arrSV = this.FetchValuesFromWeb(s, d2, d1, Market);
		arrSize = arrSV.size();
		counter = 0;
		loopCounter = 0;
		while(counter < 5 && loopCounter < arrSize){
		StockValue sv = arrSV.get(loopCounter);	
		if(sv.getVolume() > 0.0){
			
			//System.out.println(sv.getDt() + "->"+ sv.getClose());
			arrClose[counter] = sv.getClose();
			counter =counter+1;
		}
		
		loopCounter = loopCounter + 1;		
		}
		
		
		return this.generatePattern_5_5(arrClose[4], arrClose[3], arrClose[2], arrClose[1], arrClose[0]);
	}
	
	public String generatePattern_5_5(double c1,double c2,double c3,double c4,double c5){
		double max = 0.0;
		double min = 1000000.0;
		double grad;
		String pattern;
		
		int val;
		
		max = Math.max(max, c1);
		max = Math.max(max, c2);
		max = Math.max(max, c3);
		max = Math.max(max, c4);
		max = Math.max(max, c5);
		
		min = Math.min(min,c1);
		min = Math.min(min,c2);
		min = Math.min(min,c3);
		min = Math.min(min,c4);
		min = Math.min(min,c5);
		
		grad = (max-min)/5;
		
		pattern = "";
		val = (int) (Math.round((c1-min)/grad));
		pattern = pattern + Integer.toString(val)+"-";
		
		val = (int) (Math.round((c2-min)/grad));
		pattern = pattern + Integer.toString(val)+"-";
		
		val = (int) (Math.round((c3-min)/grad));
		pattern = pattern + Integer.toString(val)+"-";
		
		val = (int) (Math.round((c4-min)/grad));
		pattern = pattern + Integer.toString(val)+"-";
		
		val = (int) (Math.round((c5-min)/grad));
		pattern = pattern + Integer.toString(val);
		
		String value="";
		value = value+Double.toString(c1)+" - ";
		value = value+Double.toString(c2)+" - ";
		value = value+Double.toString(c3)+" - ";
		value = value+Double.toString(c4)+" - ";
		value = value+Double.toString(c5);
		
		System.out.println(value);
		System.out.println("Max->"+max);
		System.out.println("Min->"+min);
		System.out.println("Grad->"+grad);
		
		return pattern;
	}
	
	public ArrayList<Stock> getAllstocksManually(){
		ArrayList<Stock> as = new ArrayList<Stock>();
			
		as.add(new Stock("20MICRONS" , "1"));
		as.add(new Stock("3IINFOTECH" , "2"));
		as.add(new Stock("3MINDIA" , "3"));
		as.add(new Stock("8KMILES" , "4"));
		as.add(new Stock("A2ZINFRA" , "5"));
		as.add(new Stock("AARTIDRUGS" , "6"));
		as.add(new Stock("AARTIIND" , "7"));
		as.add(new Stock("AARVEEDEN" , "8"));
		as.add(new Stock("ABAN" , "9"));
		as.add(new Stock("ABB" , "10"));
		as.add(new Stock("ABBOTINDIA" , "11"));
		as.add(new Stock("ABFRL" , "12"));
		as.add(new Stock("ABGSHIP" , "13"));
		as.add(new Stock("ABIRLANUVO" , "14"));
		as.add(new Stock("ACC" , "15"));
		as.add(new Stock("ACCELYA" , "16"));
		as.add(new Stock("ACE" , "17"));
		as.add(new Stock("ADANIENT" , "18"));
		as.add(new Stock("ADANIPORTS" , "19"));
		as.add(new Stock("ADANIPOWER" , "20"));
		as.add(new Stock("ADANITRANS" , "21"));
		as.add(new Stock("ADFFOODS" , "22"));
		as.add(new Stock("ADHUNIK" , "23"));
		as.add(new Stock("ADHUNIKIND" , "24"));
		as.add(new Stock("ADI" , "25"));
		as.add(new Stock("ADLABS" , "26"));
		as.add(new Stock("ADORWELD" , "27"));
		as.add(new Stock("ADSL" , "28"));
		as.add(new Stock("ADVANIHOTR" , "29"));
		as.add(new Stock("ADVANTA" , "30"));
		as.add(new Stock("AEGISCHEM" , "31"));
		as.add(new Stock("AFL" , "32"));
		as.add(new Stock("AGARIND" , "33"));
		as.add(new Stock("AGCNET" , "34"));
		as.add(new Stock("AGRITECH" , "35"));
		as.add(new Stock("AGRODUTCH" , "36"));
		as.add(new Stock("AHLEAST" , "37"));
		as.add(new Stock("AHLUCONT" , "38"));
		as.add(new Stock("AHLWEST" , "39"));
		as.add(new Stock("AIAENG" , "40"));
		as.add(new Stock("AIFL" , "41"));
		as.add(new Stock("AIL" , "42"));
		as.add(new Stock("AJANTPHARM" , "43"));
		as.add(new Stock("AJMERA" , "44"));
		as.add(new Stock("AKSHOPTFBR" , "45"));
		as.add(new Stock("AKZOINDIA" , "46"));
		as.add(new Stock("ALANKIT" , "47"));
		as.add(new Stock("ALBERTDAVD" , "48"));
		as.add(new Stock("ALBK" , "49"));
		as.add(new Stock("ALCHEM" , "50"));
		as.add(new Stock("ALEMBICLTD" , "51"));
		as.add(new Stock("ALICON" , "52"));
		as.add(new Stock("ALKALI" , "53"));
		as.add(new Stock("ALKEM" , "54"));
		as.add(new Stock("ALKYLAMINE" , "55"));
		as.add(new Stock("ALLCARGO" , "56"));
		as.add(new Stock("ALLSEC" , "57"));
		as.add(new Stock("ALMONDZ" , "58"));
		as.add(new Stock("ALOKTEXT" , "59"));
		as.add(new Stock("ALPHAGEO" , "60"));
		as.add(new Stock("ALPSINDUS" , "61"));
		as.add(new Stock("ALSTOMT&D" , "62"));
		as.add(new Stock("AMARAJABAT" , "63"));
		as.add(new Stock("AMBIKCO" , "64"));
		as.add(new Stock("AMBUJACEM" , "65"));
		as.add(new Stock("AMDIND" , "66"));
		as.add(new Stock("AMRUTANJAN" , "67"));
		as.add(new Stock("AMTEKAUTO" , "68"));
		as.add(new Stock("AMTL" , "69"));
		as.add(new Stock("ANANTRAJ" , "70"));
		as.add(new Stock("ANDHRABANK" , "71"));
		as.add(new Stock("ANDHRACEMT" , "72"));
		as.add(new Stock("ANDHRSUGAR" , "73"));
		as.add(new Stock("ANGIND" , "74"));
		as.add(new Stock("ANKITMETAL" , "75"));
		as.add(new Stock("ANSALAPI" , "76"));
		as.add(new Stock("ANSALHSG" , "77"));
		as.add(new Stock("APARINDS" , "78"));
		as.add(new Stock("APCOTEXIND" , "79"));
		as.add(new Stock("APLAPOLLO" , "80"));
		as.add(new Stock("APLLTD" , "81"));
		as.add(new Stock("APOLLOHOSP" , "82"));
		as.add(new Stock("APOLLOTYRE" , "83"));
		as.add(new Stock("APTECHT" , "84"));
		as.add(new Stock("ARCHIDPLY" , "85"));
		as.add(new Stock("ARCHIES" , "86"));
		as.add(new Stock("ARCOTECH" , "87"));
		as.add(new Stock("ARIES" , "88"));
		as.add(new Stock("ARIHANT" , "89"));
		as.add(new Stock("ARMANFIN" , "90"));
		as.add(new Stock("AROGRANITE" , "91"));
		as.add(new Stock("ARROWGREEN" , "92"));
		as.add(new Stock("ARROWTEX" , "93"));
		as.add(new Stock("ARSHIYA" , "94"));
		as.add(new Stock("ARSSINFRA" , "95"));
		as.add(new Stock("ARVIND" , "96"));
		as.add(new Stock("ARVINFRA" , "97"));
		as.add(new Stock("ASAHIINDIA" , "98"));
		as.add(new Stock("ASAHISONG" , "99"));
		as.add(new Stock("ASAL" , "100"));
		as.add(new Stock("ASHAPURMIN" , "101"));
		as.add(new Stock("ASHIANA" , "102"));
		as.add(new Stock("ASHIMASYN" , "103"));
		as.add(new Stock("ASHOKA" , "104"));
		as.add(new Stock("ASHOKLEY" , "105"));
		as.add(new Stock("ASIANHOTNR" , "106"));
		as.add(new Stock("ASIANPAINT" , "107"));
		as.add(new Stock("ASIANTILES" , "108"));
		as.add(new Stock("ASIL" , "109"));
		as.add(new Stock("ASSAMCO" , "110"));
		as.add(new Stock("ASTEC" , "111"));
		as.add(new Stock("ASTRAL" , "112"));
		as.add(new Stock("ASTRAMICRO" , "113"));
		as.add(new Stock("ASTRAZEN" , "114"));
		as.add(new Stock("ATFL" , "115"));
		as.add(new Stock("ATLANTA" , "116"));
		as.add(new Stock("ATLASCYCLE" , "117"));
		as.add(new Stock("ATNINTER" , "118"));
		as.add(new Stock("ATUL" , "119"));
		as.add(new Stock("ATULAUTO" , "120"));
		as.add(new Stock("AURIONPRO" , "121"));
		as.add(new Stock("AUROPHARMA" , "122"));
		as.add(new Stock("AUSOMENT" , "123"));
		as.add(new Stock("AUSTRAL" , "124"));
		as.add(new Stock("AUTOAXLES" , "125"));
		as.add(new Stock("AUTOIND" , "126"));
		as.add(new Stock("AUTOLITIND" , "127"));
		as.add(new Stock("AVANTIFEED" , "128"));
		as.add(new Stock("AVTNPL" , "129"));
		as.add(new Stock("AXISBANK" , "130"));
		as.add(new Stock("AXISCADES" , "131"));
		as.add(new Stock("AXISGOLD" , "132"));
		as.add(new Stock("AYMSYNTEX" , "133"));
		as.add(new Stock("BAFNAPHARM" , "134"));
		as.add(new Stock("BAGFILMS" , "135"));
		as.add(new Stock("BAJAJ-AUTO" , "136"));
		as.add(new Stock("BAJAJCORP" , "137"));
		as.add(new Stock("BAJAJELEC" , "138"));
		as.add(new Stock("BAJAJFINSV" , "139"));
		as.add(new Stock("BAJAJHIND" , "140"));
		as.add(new Stock("BAJAJHLDNG" , "141"));
		as.add(new Stock("BAJFINANCE" , "142"));
		as.add(new Stock("BALAJITELE" , "143"));
		as.add(new Stock("BALAMINES" , "144"));
		as.add(new Stock("BALKRISIND" , "145"));
		as.add(new Stock("BALLARPUR" , "146"));
		as.add(new Stock("BALMLAWRIE" , "147"));
		as.add(new Stock("BALPHARMA" , "148"));
		as.add(new Stock("BALRAMCHIN" , "149"));
		as.add(new Stock("BANARBEADS" , "150"));
		as.add(new Stock("BANARISUG" , "151"));
		as.add(new Stock("BANCOINDIA" , "152"));
		as.add(new Stock("BANG" , "153"));
		as.add(new Stock("BANKBARODA" , "154"));
		as.add(new Stock("BANKBEES" , "155"));
		as.add(new Stock("BANKINDIA" , "156"));
		as.add(new Stock("BANSWRAS" , "157"));
		as.add(new Stock("BARTRONICS" , "158"));
		as.add(new Stock("BASF" , "159"));
		as.add(new Stock("BASML" , "160"));
		as.add(new Stock("BATAINDIA" , "161"));
		as.add(new Stock("BAYERCROP" , "162"));
		as.add(new Stock("BBL" , "163"));
		as.add(new Stock("BBTC" , "164"));
		as.add(new Stock("BEARDSELL" , "165"));
		as.add(new Stock("BEDMUTHA" , "166"));
		as.add(new Stock("BEL" , "167"));
		as.add(new Stock("BEML" , "168"));
		as.add(new Stock("BEPL" , "169"));
		as.add(new Stock("BERGEPAINT" , "170"));
		as.add(new Stock("BFINVEST" , "171"));
		as.add(new Stock("BFUTILITIE" , "172"));
		as.add(new Stock("BGRENERGY" , "173"));
		as.add(new Stock("BHAGERIA" , "174"));
		as.add(new Stock("BHAGYNAGAR" , "175"));
		as.add(new Stock("BHARATFIN" , "176"));
		as.add(new Stock("BHARATFORG" , "177"));
		as.add(new Stock("BHARATGEAR" , "178"));
		as.add(new Stock("BHARATIDIL" , "179"));
		as.add(new Stock("BHARATRAS" , "180"));
		as.add(new Stock("BHARATWIRE" , "181"));
		as.add(new Stock("BHARTIARTL" , "182"));
		as.add(new Stock("BHEL" , "183"));
		as.add(new Stock("BHUSANSTL" , "184"));
		as.add(new Stock("BIL" , "185"));
		as.add(new Stock("BILENERGY" , "186"));
		as.add(new Stock("BILPOWER" , "187"));
		as.add(new Stock("BINANIIND" , "188"));
		as.add(new Stock("BINDALAGRO" , "189"));
		as.add(new Stock("BIOCON" , "190"));
		as.add(new Stock("BIRLACORPN" , "191"));
		as.add(new Stock("BIRLAMONEY" , "192"));
		as.add(new Stock("BLBLIMITED" , "193"));
		as.add(new Stock("BLISSGVS" , "194"));
		as.add(new Stock("BLKASHYAP" , "195"));
		as.add(new Stock("BLUEBLENDS" , "196"));
		as.add(new Stock("BLUECHIP" , "197"));
		as.add(new Stock("BLUEDART" , "198"));
		as.add(new Stock("BLUESTARCO" , "199"));
		as.add(new Stock("BODALCHEM" , "200"));
		as.add(new Stock("BOMDYEING" , "201"));
		as.add(new Stock("BOSCHLTD" , "202"));
		as.add(new Stock("BPCL" , "203"));
		as.add(new Stock("BPL" , "204"));
		as.add(new Stock("BRFL" , "205"));
		as.add(new Stock("BRIGADE" , "206"));
		as.add(new Stock("BRITANNIA" , "207"));
		as.add(new Stock("BROOKS" , "208"));
		as.add(new Stock("BSELINFRA" , "209"));
		as.add(new Stock("BSL" , "210"));
		as.add(new Stock("BSLGOLDETF" , "211"));
		as.add(new Stock("BSLIMITED" , "212"));
		as.add(new Stock("BSLNIFTY" , "213"));
		as.add(new Stock("BURNPUR" , "214"));
		as.add(new Stock("BUTTERFLY" , "215"));
		as.add(new Stock("BVCL" , "216"));
		as.add(new Stock("BYKE" , "217"));
		as.add(new Stock("CADILAHC" , "218"));
		as.add(new Stock("CAIRN" , "219"));
		as.add(new Stock("CAMLINFINE" , "220"));
		as.add(new Stock("CANBK" , "221"));
		as.add(new Stock("CANDC" , "222"));
		as.add(new Stock("CANFINHOME" , "223"));
		as.add(new Stock("CANTABIL" , "224"));
		as.add(new Stock("CAPF" , "225"));
		as.add(new Stock("CAPLIPOINT" , "226"));
		as.add(new Stock("CARBORUNIV" , "227"));
		as.add(new Stock("CAREERP" , "228"));
		as.add(new Stock("CARERATING" , "229"));
		as.add(new Stock("CASTEXTECH" , "230"));
		as.add(new Stock("CASTROLIND" , "231"));
		as.add(new Stock("CCCL" , "232"));
		as.add(new Stock("CCHHL" , "233"));
		as.add(new Stock("CCL" , "234"));
		as.add(new Stock("CEATLTD" , "235"));
		as.add(new Stock("CEBBCO" , "236"));
		as.add(new Stock("CELEBRITY" , "237"));
		as.add(new Stock("CELESTIAL" , "238"));
		as.add(new Stock("CENTENKA" , "239"));
		as.add(new Stock("CENTEXT" , "240"));
		as.add(new Stock("CENTRALBK" , "241"));
		as.add(new Stock("CENTUM" , "242"));
		as.add(new Stock("CENTURYPLY" , "243"));
		as.add(new Stock("CENTURYTEX" , "244"));
		as.add(new Stock("CERA" , "245"));
		as.add(new Stock("CEREBRAINT" , "246"));
		as.add(new Stock("CESC" , "247"));
		as.add(new Stock("CGCL" , "248"));
		as.add(new Stock("CHAMBLFERT" , "249"));
		as.add(new Stock("CHEMFALKAL" , "250"));
		as.add(new Stock("CHENNPETRO" , "251"));
		as.add(new Stock("CHOLAFIN" , "252"));
		as.add(new Stock("CHROMATIC" , "253"));
		as.add(new Stock("CIGNITITEC" , "254"));
		as.add(new Stock("CIMMCO" , "255"));
		as.add(new Stock("CINELINE" , "256"));
		as.add(new Stock("CINEVISTA" , "257"));
		as.add(new Stock("CIPLA" , "258"));
		as.add(new Stock("CLNINDIA" , "259"));
		as.add(new Stock("CNOVAPETRO" , "260"));
		as.add(new Stock("COALINDIA" , "261"));
		as.add(new Stock("COFFEEDAY" , "262"));
		as.add(new Stock("COLPAL" , "263"));
		as.add(new Stock("COMPINFO" , "264"));
		as.add(new Stock("COMPUSOFT" , "265"));
		as.add(new Stock("CONCOR" , "266"));
		as.add(new Stock("CONSOFINVT" , "267"));
		as.add(new Stock("CONTROLPR" , "268"));
		as.add(new Stock("CORDSCABLE" , "269"));
		as.add(new Stock("COROMANDEL" , "270"));
		as.add(new Stock("CORPBANK" , "271"));
		as.add(new Stock("COSMOFILMS" , "272"));
		as.add(new Stock("COUNCODOS" , "273"));
		as.add(new Stock("COX&KINGS" , "274"));
		as.add(new Stock("CPSEETF" , "275"));
		as.add(new Stock("CREATIVEYE" , "276"));
		as.add(new Stock("CREST" , "277"));
		as.add(new Stock("CRISIL" , "278"));
		as.add(new Stock("CRMFGETF" , "279"));
		as.add(new Stock("CROMPGREAV" , "280"));
		as.add(new Stock("CROMPTON" , "281"));
		as.add(new Stock("CTE" , "282"));
		as.add(new Stock("CUB" , "283"));
		as.add(new Stock("CUMMINSIND" , "284"));
		as.add(new Stock("CURATECH" , "285"));
		as.add(new Stock("CYBERTECH" , "286"));
		as.add(new Stock("CYIENT" , "287"));
		as.add(new Stock("DAAWAT" , "288"));
		as.add(new Stock("DABUR" , "289"));
		as.add(new Stock("DALMIABHA" , "290"));
		as.add(new Stock("DALMIASUG" , "291"));
		as.add(new Stock("DAMODARIND" , "292"));
		as.add(new Stock("DATAMATICS" , "293"));
		as.add(new Stock("DBCORP" , "294"));
		as.add(new Stock("DBREALTY" , "295"));
		as.add(new Stock("DBSTOCKBRO" , "296"));
		as.add(new Stock("DCBBANK" , "297"));
		as.add(new Stock("DCM" , "298"));
		as.add(new Stock("DCMSHRIRAM" , "299"));
		as.add(new Stock("DCW" , "300"));
		as.add(new Stock("DECCANCE" , "301"));
		as.add(new Stock("DEEPAKFERT" , "302"));
		as.add(new Stock("DEEPAKNTR" , "303"));
		as.add(new Stock("DEEPIND" , "304"));
		as.add(new Stock("DELTACORP" , "305"));
		as.add(new Stock("DELTAMAGNT" , "306"));
		as.add(new Stock("DEN" , "307"));
		as.add(new Stock("DENABANK" , "308"));
		as.add(new Stock("DENORA" , "309"));
		as.add(new Stock("DHAMPURSUG" , "310"));
		as.add(new Stock("DHANBANK" , "311"));
		as.add(new Stock("DHANUKA" , "312"));
		as.add(new Stock("DHARSUGAR" , "313"));
		as.add(new Stock("DHFL" , "314"));
		as.add(new Stock("DHUNINV" , "315"));
		as.add(new Stock("DIAPOWER" , "316"));
		as.add(new Stock("DICIND" , "317"));
		as.add(new Stock("DIGJAMLTD" , "318"));
		as.add(new Stock("DISHMAN" , "319"));
		as.add(new Stock("DISHTV" , "320"));
		as.add(new Stock("DIVISLAB" , "321"));
		as.add(new Stock("DLF" , "322"));
		as.add(new Stock("DLINKINDIA" , "323"));
		as.add(new Stock("DOLPHINOFF" , "324"));
		as.add(new Stock("DONEAR" , "325"));
		as.add(new Stock("DPL" , "326"));
		as.add(new Stock("DPSCLTD" , "327"));
		as.add(new Stock("DQE" , "328"));
		as.add(new Stock("DREDGECORP" , "329"));
		as.add(new Stock("DRREDDY" , "330"));
		as.add(new Stock("DSKULKARNI" , "331"));
		as.add(new Stock("DSSL" , "332"));
		as.add(new Stock("DTIL" , "333"));
		as.add(new Stock("DUCON" , "334"));
		as.add(new Stock("DWARKESH" , "335"));
		as.add(new Stock("DYNAMATECH" , "336"));
		as.add(new Stock("EASTSILK" , "337"));
		as.add(new Stock("EASUNREYRL" , "338"));
		as.add(new Stock("ECEIND" , "339"));
		as.add(new Stock("ECLERX" , "340"));
		as.add(new Stock("EDELWEISS" , "341"));
		as.add(new Stock("EDL" , "342"));
		as.add(new Stock("EDUCOMP" , "343"));
		as.add(new Stock("EICHERMOT" , "344"));
		as.add(new Stock("EIDPARRY" , "345"));
		as.add(new Stock("EIHAHOTELS" , "346"));
		as.add(new Stock("EIHOTEL" , "347"));
		as.add(new Stock("EKC" , "348"));
		as.add(new Stock("ELAND" , "349"));
		as.add(new Stock("ELECON" , "350"));
		as.add(new Stock("ELECTCAST" , "351"));
		as.add(new Stock("ELECTHERM" , "352"));
		as.add(new Stock("ELGIEQUIP" , "353"));
		as.add(new Stock("ELGIRUBCO" , "354"));
		as.add(new Stock("EMAMIINFRA" , "355"));
		as.add(new Stock("EMAMILTD" , "356"));
		as.add(new Stock("EMCO" , "357"));
		as.add(new Stock("EMKAY" , "358"));
		as.add(new Stock("EMMBI" , "359"));
		as.add(new Stock("ENERGYDEV" , "360"));
		as.add(new Stock("ENGINERSIN" , "361"));
		as.add(new Stock("ENIL" , "362"));
		as.add(new Stock("EON" , "363"));
		as.add(new Stock("EQ30" , "364"));
		as.add(new Stock("EQUITAS" , "365"));
		as.add(new Stock("EROSMEDIA" , "366"));
		as.add(new Stock("ESABINDIA" , "367"));
		as.add(new Stock("ESCORTS" , "368"));
		as.add(new Stock("ESL" , "369"));
		as.add(new Stock("ESSARSHPNG" , "370"));
		as.add(new Stock("ESSDEE" , "371"));
		as.add(new Stock("ESSELPACK" , "372"));
		as.add(new Stock("ESTER" , "373"));
		as.add(new Stock("EUROCERA" , "374"));
		as.add(new Stock("EUROTEXIND" , "375"));
		as.add(new Stock("EVEREADY" , "376"));
		as.add(new Stock("EVERESTIND" , "377"));
		as.add(new Stock("EVERONN" , "378"));
		as.add(new Stock("EXCEL" , "379"));
		as.add(new Stock("EXCELCROP" , "380"));
		as.add(new Stock("EXCELINDUS" , "381"));
		as.add(new Stock("EXIDEIND" , "382"));
		as.add(new Stock("FACT" , "383"));
		as.add(new Stock("FAGBEARING" , "384"));
		as.add(new Stock("FARMAXIND" , "385"));
		as.add(new Stock("FCEL" , "386"));
		as.add(new Stock("FCL" , "387"));
		as.add(new Stock("FCSSOFT" , "388"));
		as.add(new Stock("FDC" , "389"));
		as.add(new Stock("FEDDERLOYD" , "390"));
		as.add(new Stock("FEDERALBNK" , "391"));
		as.add(new Stock("FEL" , "392"));
		as.add(new Stock("FELDVR" , "393"));
		as.add(new Stock("FIEMIND" , "394"));
		as.add(new Stock("FILATEX" , "395"));
		as.add(new Stock("FINANTECH" , "396"));
		as.add(new Stock("FINCABLES" , "397"));
		as.add(new Stock("FINPIPE" , "398"));
		as.add(new Stock("FIRSTWIN" , "399"));
		as.add(new Stock("FLEXITUFF" , "400"));
		as.add(new Stock("FLFL" , "401"));
		as.add(new Stock("FMGOETZE" , "402"));
		as.add(new Stock("FMNL" , "403"));
		as.add(new Stock("FORTIS" , "404"));
		as.add(new Stock("FOSECOIND" , "405"));
		as.add(new Stock("FSL" , "406"));
		as.add(new Stock("GABRIEL" , "407"));
		as.add(new Stock("GAEL" , "408"));
		as.add(new Stock("GAIL" , "409"));
		as.add(new Stock("GAL" , "410"));
		as.add(new Stock("GALLANTT" , "411"));
		as.add(new Stock("GALLISPAT" , "412"));
		as.add(new Stock("GAMMNINFRA" , "413"));
		as.add(new Stock("GAMMONIND" , "414"));
		as.add(new Stock("GANDHITUBE" , "415"));
		as.add(new Stock("GANECOS" , "416"));
		as.add(new Stock("GANESHHOUC" , "417"));
		as.add(new Stock("GANGOTRI" , "418"));
		as.add(new Stock("GARDENSILK" , "419"));
		as.add(new Stock("GARWALLROP" , "420"));
		as.add(new Stock("GATI" , "421"));
		as.add(new Stock("GAYAPROJ" , "422"));
		as.add(new Stock("GDL" , "423"));
		as.add(new Stock("GEECEE" , "424"));
		as.add(new Stock("GEMINI" , "425"));
		as.add(new Stock("GENESYS" , "426"));
		as.add(new Stock("GENUSPAPER" , "427"));
		as.add(new Stock("GENUSPOWER" , "428"));
		as.add(new Stock("GEOJITBNPP" , "429"));
		as.add(new Stock("GEOMETRIC" , "430"));
		as.add(new Stock("GESHIP" , "431"));
		as.add(new Stock("GHCL" , "432"));
		as.add(new Stock("GICHSGFIN" , "433"));
		as.add(new Stock("GILLANDERS" , "434"));
		as.add(new Stock("GILLETTE" , "435"));
		as.add(new Stock("GINNIFILA" , "436"));
		as.add(new Stock("GIPCL" , "437"));
		as.add(new Stock("GISOLUTION" , "438"));
		as.add(new Stock("GITANJALI" , "439"));
		as.add(new Stock("GKWLIMITED" , "440"));
		as.add(new Stock("GLAXO" , "441"));
		as.add(new Stock("GLENMARK" , "442"));
		as.add(new Stock("GLOBALVECT" , "443"));
		as.add(new Stock("GLOBOFFS" , "444"));
		as.add(new Stock("GLOBUSSPR" , "445"));
		as.add(new Stock("GMBREW" , "446"));
		as.add(new Stock("GMDCLTD" , "447"));
		as.add(new Stock("GMRINFRA" , "448"));
		as.add(new Stock("GNFC" , "449"));
		as.add(new Stock("GOACARBON" , "450"));
		as.add(new Stock("GOCLCORP" , "451"));
		as.add(new Stock("GODFRYPHLP" , "452"));
		as.add(new Stock("GODREJCP" , "453"));
		as.add(new Stock("GODREJIND" , "454"));
		as.add(new Stock("GODREJPROP" , "455"));
		as.add(new Stock("GOKEX" , "456"));
		as.add(new Stock("GOKUL" , "457"));
		as.add(new Stock("GOKULAGRO" , "458"));
		as.add(new Stock("GOLDBEES" , "459"));
		as.add(new Stock("GOLDENTOBC" , "460"));
		as.add(new Stock("GOLDIAM" , "461"));
		as.add(new Stock("GOLDINFRA" , "462"));
		as.add(new Stock("GOLDIWIN" , "463"));
		as.add(new Stock("GOLDSHARE" , "464"));
		as.add(new Stock("GOLDTECH" , "465"));
		as.add(new Stock("GOODLUCK" , "466"));
		as.add(new Stock("GPIL" , "467"));
		as.add(new Stock("GPPL" , "468"));
		as.add(new Stock("GPTINFRA" , "469"));
		as.add(new Stock("GRANULES" , "470"));
		as.add(new Stock("GRAPHITE" , "471"));
		as.add(new Stock("GRASIM" , "472"));
		as.add(new Stock("GRAVITA" , "473"));
		as.add(new Stock("GREAVESCOT" , "474"));
		as.add(new Stock("GREENFIRE" , "475"));
		as.add(new Stock("GREENLAM" , "476"));
		as.add(new Stock("GREENPLY" , "477"));
		as.add(new Stock("GREENPOWER" , "478"));
		as.add(new Stock("GRINDWELL" , "479"));
		as.add(new Stock("GRPLTD" , "480"));
		as.add(new Stock("GRUH" , "481"));
		as.add(new Stock("GSCLCEMENT" , "482"));
		as.add(new Stock("GSFC" , "483"));
		as.add(new Stock("GSKCONS" , "484"));
		as.add(new Stock("GSPL" , "485"));
		as.add(new Stock("GSS" , "486"));
		as.add(new Stock("GTL" , "487"));
		as.add(new Stock("GTLINFRA" , "488"));
		as.add(new Stock("GTNIND" , "489"));
		as.add(new Stock("GTNTEX" , "490"));
		as.add(new Stock("GTOFFSHORE" , "491"));
		as.add(new Stock("GUFICBIO" , "492"));
		as.add(new Stock("GUJALKALI" , "493"));
		as.add(new Stock("GUJAPOLLO" , "494"));
		as.add(new Stock("GUJFLUORO" , "495"));
		as.add(new Stock("GUJGASLTD" , "496"));
		as.add(new Stock("GUJNRECOKE" , "497"));
		as.add(new Stock("GUJNREDVR" , "498"));
		as.add(new Stock("GULFOILLUB" , "499"));
		as.add(new Stock("GULFPETRO" , "500"));
		as.add(new Stock("GULPOLY" , "501"));
		as.add(new Stock("GVKPIL" , "502"));
		as.add(new Stock("HANUNG" , "503"));
		as.add(new Stock("HARITASEAT" , "504"));
		as.add(new Stock("HARRMALAYA" , "505"));
		as.add(new Stock("HATHWAY" , "506"));
		as.add(new Stock("HATSUN" , "507"));
		as.add(new Stock("HAVELLS" , "508"));
		as.add(new Stock("HBLPOWER" , "509"));
		as.add(new Stock("HBSTOCK" , "510"));
		as.add(new Stock("HCC" , "511"));
		as.add(new Stock("HCG" , "512"));
		as.add(new Stock("HCIL" , "513"));
		as.add(new Stock("HCL-INSYS" , "514"));
		as.add(new Stock("HCLTECH" , "515"));
		as.add(new Stock("HDFC" , "516"));
		as.add(new Stock("HDFCBANK" , "517"));
		as.add(new Stock("HDFCMFGETF" , "518"));
		as.add(new Stock("HDFCNIFETF" , "519"));
		as.add(new Stock("HDIL" , "520"));
		as.add(new Stock("HEG" , "521"));
		as.add(new Stock("HEIDELBERG" , "522"));
		as.add(new Stock("HERCULES" , "523"));
		as.add(new Stock("HERITGFOOD" , "524"));
		as.add(new Stock("HEROMOTOCO" , "525"));
		as.add(new Stock("HESTERBIO" , "526"));
		as.add(new Stock("HEXATRADEX" , "527"));
		as.add(new Stock("HEXAWARE" , "528"));
		as.add(new Stock("HFCL" , "529"));
		as.add(new Stock("HGS" , "530"));
		as.add(new Stock("HIKAL" , "531"));
		as.add(new Stock("HIL" , "532"));
		as.add(new Stock("HILTON" , "533"));
		as.add(new Stock("HIMATSEIDE" , "534"));
		as.add(new Stock("HINDALCO" , "535"));
		as.add(new Stock("HINDCOMPOS" , "536"));
		as.add(new Stock("HINDCOPPER" , "537"));
		as.add(new Stock("HINDDORROL" , "538"));
		as.add(new Stock("HINDMOTORS" , "539"));
		as.add(new Stock("HINDNATGLS" , "540"));
		as.add(new Stock("HINDOILEXP" , "541"));
		as.add(new Stock("HINDPETRO" , "542"));
		as.add(new Stock("HINDSYNTEX" , "543"));
		as.add(new Stock("HINDUJAFO" , "544"));
		as.add(new Stock("HINDUJAVEN" , "545"));
		as.add(new Stock("HINDUNILVR" , "546"));
		as.add(new Stock("HINDZINC" , "547"));
		as.add(new Stock("HIRECT" , "548"));
		as.add(new Stock("HITACHIHOM" , "549"));
		as.add(new Stock("HITECHGEAR" , "550"));
		as.add(new Stock("HITECHPLAS" , "551"));
		as.add(new Stock("HMVL" , "552"));
		as.add(new Stock("HNGSNGBEES" , "553"));
		as.add(new Stock("HOCL" , "554"));
		as.add(new Stock("HONAUT" , "555"));
		as.add(new Stock("HONDAPOWER" , "556"));
		as.add(new Stock("HOTELEELA" , "557"));
		as.add(new Stock("HOVS" , "558"));
		as.add(new Stock("HSIL" , "559"));
		as.add(new Stock("HTMEDIA" , "560"));
		as.add(new Stock("HUBTOWN" , "561"));
		as.add(new Stock("IBREALEST" , "562"));
		as.add(new Stock("IBULHSGFIN" , "563"));
		as.add(new Stock("IBVENTURES" , "564"));
		as.add(new Stock("IBWSL" , "565"));
		as.add(new Stock("ICICIBANK" , "566"));
		as.add(new Stock("ICIL" , "567"));
		as.add(new Stock("ICRA" , "568"));
		as.add(new Stock("ICSA" , "569"));
		as.add(new Stock("IDBI" , "570"));
		as.add(new Stock("IDBIGOLD" , "571"));
		as.add(new Stock("IDEA" , "572"));
		as.add(new Stock("IDFC" , "573"));
		as.add(new Stock("IDFCBANK" , "574"));
		as.add(new Stock("IFBAGRO" , "575"));
		as.add(new Stock("IFBIND" , "576"));
		as.add(new Stock("IFCI" , "577"));
		as.add(new Stock("IFGLREFRAC" , "578"));
		as.add(new Stock("IGARASHI" , "579"));
		as.add(new Stock("IGL" , "580"));
		as.add(new Stock("IGPL" , "581"));
		as.add(new Stock("IIFL" , "582"));
		as.add(new Stock("IITL" , "583"));
		as.add(new Stock("IL&FSENGG" , "584"));
		as.add(new Stock("IL&FSTRANS" , "585"));
		as.add(new Stock("IMFA" , "586"));
		as.add(new Stock("IMPAL" , "587"));
		as.add(new Stock("IMPEXFERRO" , "588"));
		as.add(new Stock("INDBANK" , "589"));
		as.add(new Stock("INDHOTEL" , "590"));
		as.add(new Stock("INDIACEM" , "591"));
		as.add(new Stock("INDIAGLYCO" , "592"));
		as.add(new Stock("INDIANB" , "593"));
		as.add(new Stock("INDIANCARD" , "594"));
		as.add(new Stock("INDIANHUME" , "595"));
		as.add(new Stock("INDIGO" , "596"));
		as.add(new Stock("INDLMETER" , "597"));
		as.add(new Stock("INDNIPPON" , "598"));
		as.add(new Stock("INDOCO" , "599"));
		as.add(new Stock("INDORAMA" , "600"));
		as.add(new Stock("INDOSOLAR" , "601"));
		as.add(new Stock("INDOTECH" , "602"));
		as.add(new Stock("INDOTHAI" , "603"));
		as.add(new Stock("INDRAMEDCO" , "604"));
		as.add(new Stock("INDSWFTLAB" , "605"));
		as.add(new Stock("INDTERRAIN" , "606"));
		as.add(new Stock("INDUSINDBK" , "607"));
		as.add(new Stock("INEOSSTYRO" , "608"));
		as.add(new Stock("INFIBEAM" , "609"));
		as.add(new Stock("INFINITE" , "610"));
		as.add(new Stock("INFOMEDIA" , "611"));
		as.add(new Stock("INFRABEES" , "612"));
		as.add(new Stock("INFRATEL" , "613"));
		as.add(new Stock("INFY" , "614"));
		as.add(new Stock("INGERRAND" , "615"));
		as.add(new Stock("INOXLEISUR" , "616"));
		as.add(new Stock("INOXWIND" , "617"));
		as.add(new Stock("INSECTICID" , "618"));
		as.add(new Stock("INTELLECT" , "619"));
		as.add(new Stock("INVENTURE" , "620"));
		as.add(new Stock("IOB" , "621"));
		as.add(new Stock("IOC" , "622"));
		as.add(new Stock("IOLCP" , "623"));
		as.add(new Stock("IPAPPM" , "624"));
		as.add(new Stock("IPCALAB" , "625"));
		as.add(new Stock("IRB" , "626"));
		as.add(new Stock("ISFT" , "627"));
		as.add(new Stock("ISMTLTD" , "628"));
		as.add(new Stock("ITC" , "629"));
		as.add(new Stock("ITDCEM" , "630"));
		as.add(new Stock("ITI" , "631"));
		as.add(new Stock("IVC" , "632"));
		as.add(new Stock("IVP" , "633"));
		as.add(new Stock("IVRCLINFRA" , "634"));
		as.add(new Stock("IVZINGOLD" , "635"));
		as.add(new Stock("IVZINNIFTY" , "636"));
		as.add(new Stock("IZMO" , "637"));
		as.add(new Stock("J&KBANK" , "638"));
		as.add(new Stock("JAGRAN" , "639"));
		as.add(new Stock("JAGSNPHARM" , "640"));
		as.add(new Stock("JAIBALAJI" , "641"));
		as.add(new Stock("JAICORPLTD" , "642"));
		as.add(new Stock("JAIHINDPRO" , "643"));
		as.add(new Stock("JAMNAAUTO" , "644"));
		as.add(new Stock("JAYAGROGN" , "645"));
		as.add(new Stock("JAYBARMARU" , "646"));
		as.add(new Stock("JAYNECOIND" , "647"));
		as.add(new Stock("JAYSREETEA" , "648"));
		as.add(new Stock("JBCHEPHARM" , "649"));
		as.add(new Stock("JBFIND" , "650"));
		as.add(new Stock("JBMA" , "651"));
		as.add(new Stock("JENSONICOL" , "652"));
		as.add(new Stock("JETAIRWAYS" , "653"));
		as.add(new Stock("JHS" , "654"));
		as.add(new Stock("JIKIND" , "655"));
		as.add(new Stock("JINDALPHOT" , "656"));
		as.add(new Stock("JINDALPOLY" , "657"));
		as.add(new Stock("JINDALSAW" , "658"));
		as.add(new Stock("JINDALSTEL" , "659"));
		as.add(new Stock("JINDCOT" , "660"));
		as.add(new Stock("JINDRILL" , "661"));
		as.add(new Stock("JINDWORLD" , "662"));
		as.add(new Stock("JISLDVREQS" , "663"));
		as.add(new Stock("JISLJALEQS" , "664"));
		as.add(new Stock("JKCEMENT" , "665"));
		as.add(new Stock("JKIL" , "666"));
		as.add(new Stock("JKLAKSHMI" , "667"));
		as.add(new Stock("JKPAPER" , "668"));
		as.add(new Stock("JKTYRE" , "669"));
		as.add(new Stock("JMA" , "670"));
		as.add(new Stock("JMCPROJECT" , "671"));
		as.add(new Stock("JMFINANCIL" , "672"));
		as.add(new Stock("JMTAUTOLTD" , "673"));
		as.add(new Stock("JOCIL" , "674"));
		as.add(new Stock("JPASSOCIAT" , "675"));
		as.add(new Stock("JPINFRATEC" , "676"));
		as.add(new Stock("JPOLYINVST" , "677"));
		as.add(new Stock("JPPOWER" , "678"));
		as.add(new Stock("JSL" , "679"));
		as.add(new Stock("JSLHISAR" , "680"));
		as.add(new Stock("JSWENERGY" , "681"));
		as.add(new Stock("JSWHL" , "682"));
		as.add(new Stock("JSWSTEEL" , "683"));
		as.add(new Stock("JUBILANT" , "684"));
		as.add(new Stock("JUBLFOOD" , "685"));
		as.add(new Stock("JUBLINDS" , "686"));
		as.add(new Stock("JUNIORBEES" , "687"));
		as.add(new Stock("JUSTDIAL" , "688"));
		as.add(new Stock("JVLAGRO" , "689"));
		as.add(new Stock("JYOTHYLAB" , "690"));
		as.add(new Stock("JYOTISTRUC" , "691"));
		as.add(new Stock("KABRAEXTRU" , "692"));
		as.add(new Stock("KAJARIACER" , "693"));
		as.add(new Stock("KAKATCEM" , "694"));
		as.add(new Stock("KALINDEE" , "695"));
		as.add(new Stock("KALPATPOWR" , "696"));
		as.add(new Stock("KAMATHOTEL" , "697"));
		as.add(new Stock("KAMDHENU" , "698"));
		as.add(new Stock("KANANIIND" , "699"));
		as.add(new Stock("KANORICHEM" , "700"));
		as.add(new Stock("KANSAINER" , "701"));
		as.add(new Stock("KARMAENG" , "702"));
		as.add(new Stock("KARURVYSYA" , "703"));
		as.add(new Stock("KAUSHALYA" , "704"));
		as.add(new Stock("KAVVERITEL" , "705"));
		as.add(new Stock("KAYA" , "706"));
		as.add(new Stock("KCP" , "707"));
		as.add(new Stock("KCPSUGIND" , "708"));
		as.add(new Stock("KDDL" , "709"));
		as.add(new Stock("KEC" , "710"));
		as.add(new Stock("KECL" , "711"));
		as.add(new Stock("KEI" , "712"));
		as.add(new Stock("KELLTONTEC" , "713"));
		as.add(new Stock("KESARENT" , "714"));
		as.add(new Stock("KESORAMIND" , "715"));
		as.add(new Stock("KGL" , "716"));
		as.add(new Stock("KHAITANELE" , "717"));
		as.add(new Stock("KHANDSE" , "718"));
		as.add(new Stock("KICL" , "719"));
		as.add(new Stock("KILITCH" , "720"));
		as.add(new Stock("KIRIINDUS" , "721"));
		as.add(new Stock("KIRLOSBROS" , "722"));
		as.add(new Stock("KIRLOSENG" , "723"));
		as.add(new Stock("KIRLOSIND" , "724"));
		as.add(new Stock("KITEX" , "725"));
		as.add(new Stock("KKCL" , "726"));
		as.add(new Stock("KMSUGAR" , "727"));
		as.add(new Stock("KNRCON" , "728"));
		as.add(new Stock("KOHINOOR" , "729"));
		as.add(new Stock("KOKUYOCMLN" , "730"));
		as.add(new Stock("KOLTEPATIL" , "731"));
		as.add(new Stock("KOPRAN" , "732"));
		as.add(new Stock("KOTAKBANK" , "733"));
		as.add(new Stock("KOTAKBKETF" , "734"));
		as.add(new Stock("KOTAKGOLD" , "735"));
		as.add(new Stock("KOTAKNIFTY" , "736"));
		as.add(new Stock("KOTAKNV20" , "737"));
		as.add(new Stock("KOTAKPSUBK" , "738"));
		as.add(new Stock("KOTARISUG" , "739"));
		as.add(new Stock("KOTHARIPET" , "740"));
		as.add(new Stock("KOTHARIPRO" , "741"));
		as.add(new Stock("KPIT" , "742"));
		as.add(new Stock("KPRMILL" , "743"));
		as.add(new Stock("KRBL" , "744"));
		as.add(new Stock("KRIDHANINF" , "745"));
		as.add(new Stock("KSBPUMPS" , "746"));
		as.add(new Stock("KSCL" , "747"));
		as.add(new Stock("KSERASERA" , "748"));
		as.add(new Stock("KSK" , "749"));
		as.add(new Stock("KSL" , "750"));
		as.add(new Stock("KTIL" , "751"));
		as.add(new Stock("KTKBANK" , "752"));
		as.add(new Stock("KWALITY" , "753"));
		as.add(new Stock("L&TFH" , "754"));
		as.add(new Stock("LAKPRE" , "755"));
		as.add(new Stock("LAKSHMIEFL" , "756"));
		as.add(new Stock("LAKSHVILAS" , "757"));
		as.add(new Stock("LALPATHLAB" , "758"));
		as.add(new Stock("LAMBODHARA" , "759"));
		as.add(new Stock("LAOPALA" , "760"));
		as.add(new Stock("LAXMIMACH" , "761"));
		as.add(new Stock("LCCINFOTEC" , "762"));
		as.add(new Stock("LGBBROSLTD" , "763"));
		as.add(new Stock("LGBFORGE" , "764"));
		as.add(new Stock("LIBERTSHOE" , "765"));
		as.add(new Stock("LICHSGFIN" , "766"));
		as.add(new Stock("LICNETFGSC" , "767"));
		as.add(new Stock("LINCOLN" , "768"));
		as.add(new Stock("LINCPEN" , "769"));
		as.add(new Stock("LINDEINDIA" , "770"));
		as.add(new Stock("LIQUIDBEES" , "771"));
		as.add(new Stock("LITL" , "772"));
		as.add(new Stock("LLOYDELENG" , "773"));
		as.add(new Stock("LML" , "774"));
		as.add(new Stock("LOKESHMACH" , "775"));
		as.add(new Stock("LOTUSEYE" , "776"));
		as.add(new Stock("LOVABLE" , "777"));
		as.add(new Stock("LPDC" , "778"));
		as.add(new Stock("LT" , "779"));
		as.add(new Stock("LTI" , "780"));
		as.add(new Stock("LUMAXIND" , "781"));
		as.add(new Stock("LUMAXTECH" , "782"));
		as.add(new Stock("LUPIN" , "783"));
		as.add(new Stock("LUXIND" , "784"));
		as.add(new Stock("LYCOS" , "785"));
		as.add(new Stock("LYKALABS" , "786"));
		as.add(new Stock("LYPSAGEMS" , "787"));
		as.add(new Stock("M&M" , "788"));
		as.add(new Stock("M&MFIN" , "789"));
		as.add(new Stock("M100" , "790"));
		as.add(new Stock("M50" , "791"));
		as.add(new Stock("MAANALU" , "792"));
		as.add(new Stock("MADHAV" , "793"));
		as.add(new Stock("MADHUCON" , "794"));
		as.add(new Stock("MADRASFERT" , "795"));
		as.add(new Stock("MAGMA" , "796"));
		as.add(new Stock("MAGNUM" , "797"));
		as.add(new Stock("MAHABANK" , "798"));
		as.add(new Stock("MAHASTEEL" , "799"));
		as.add(new Stock("MAHINDCIE" , "800"));
		as.add(new Stock("MAHLIFE" , "801"));
		as.add(new Stock("MAHSCOOTER" , "802"));
		as.add(new Stock("MAHSEAMLES" , "803"));
		as.add(new Stock("MAITHANALL" , "804"));
		as.add(new Stock("MAJESCO" , "805"));
		as.add(new Stock("MALUPAPER" , "806"));
		as.add(new Stock("MANAKALUCO" , "807"));
		as.add(new Stock("MANAKCOAT" , "808"));
		as.add(new Stock("MANAKINDST" , "809"));
		as.add(new Stock("MANAKSIA" , "810"));
		as.add(new Stock("MANAKSTEEL" , "811"));
		as.add(new Stock("MANALIPETC" , "812"));
		as.add(new Stock("MANAPPURAM" , "813"));
		as.add(new Stock("MANDHANA" , "814"));
		as.add(new Stock("MANGALAM" , "815"));
		as.add(new Stock("MANGCHEFER" , "816"));
		as.add(new Stock("MANGLMCEM" , "817"));
		as.add(new Stock("MANGTIMBER" , "818"));
		as.add(new Stock("MANINDS" , "819"));
		as.add(new Stock("MANINFRA" , "820"));
		as.add(new Stock("MANPASAND" , "821"));
		as.add(new Stock("MANUGRAPH" , "822"));
		as.add(new Stock("MARALOVER" , "823"));
		as.add(new Stock("MARICO" , "824"));
		as.add(new Stock("MARKSANS" , "825"));
		as.add(new Stock("MARUTI" , "826"));
		as.add(new Stock("MASTEK" , "827"));
		as.add(new Stock("MAWANASUG" , "828"));
		as.add(new Stock("MAXINDIA" , "829"));
		as.add(new Stock("MAXVIL" , "830"));
		as.add(new Stock("MAXWELL" , "831"));
		as.add(new Stock("MAYURUNIQ" , "832"));
		as.add(new Stock("MBECL" , "833"));
		as.add(new Stock("MBLINFRA" , "834"));
		as.add(new Stock("MCDHOLDING" , "835"));
		as.add(new Stock("MCDOWELL-N" , "836"));
		as.add(new Stock("MCLEODRUSS" , "837"));
		as.add(new Stock("MCX" , "838"));
		as.add(new Stock("MEGH" , "839"));
		as.add(new Stock("MELSTAR" , "840"));
		as.add(new Stock("MENONBE" , "841"));
		as.add(new Stock("MEP" , "842"));
		as.add(new Stock("MERCATOR" , "843"));
		as.add(new Stock("MERCK" , "844"));
		as.add(new Stock("METALFORGE" , "845"));
		as.add(new Stock("METKORE" , "846"));
		as.add(new Stock("MFSL" , "847"));
		as.add(new Stock("MGL" , "848"));
		as.add(new Stock("MHRIL" , "849"));
		as.add(new Stock("MIC" , "850"));
		as.add(new Stock("MICROSEC" , "851"));
		as.add(new Stock("MIDCAPIWIN" , "852"));
		as.add(new Stock("MINDACORP" , "853"));
		as.add(new Stock("MINDAIND" , "854"));
		as.add(new Stock("MINDTREE" , "855"));
		as.add(new Stock("MIRCELECTR" , "856"));
		as.add(new Stock("MIRZAINT" , "857"));
		as.add(new Stock("MMFL" , "858"));
		as.add(new Stock("MMTC" , "859"));
		as.add(new Stock("MOHITIND" , "860"));
		as.add(new Stock("MOIL" , "861"));
		as.add(new Stock("MOLDTECH" , "862"));
		as.add(new Stock("MOLDTKPAC" , "863"));
		as.add(new Stock("MONNETISPA" , "864"));
		as.add(new Stock("MONSANTO" , "865"));
		as.add(new Stock("MONTECARLO" , "866"));
		as.add(new Stock("MORARJEE" , "867"));
		as.add(new Stock("MOREPENLAB" , "868"));
		as.add(new Stock("MOSERBAER" , "869"));
		as.add(new Stock("MOTHERSUMI" , "870"));
		as.add(new Stock("MOTILALOFS" , "871"));
		as.add(new Stock("MPHASIS" , "872"));
		as.add(new Stock("MPSLTD" , "873"));
		as.add(new Stock("MRF" , "874"));
		as.add(new Stock("MRO-TEK" , "875"));
		as.add(new Stock("MRPL" , "876"));
		as.add(new Stock("MSPL" , "877"));
		as.add(new Stock("MTEDUCARE" , "878"));
		as.add(new Stock("MTNL" , "879"));
		as.add(new Stock("MUKANDENGG" , "880"));
		as.add(new Stock("MUKANDLTD" , "881"));
		as.add(new Stock("MUKTAARTS" , "882"));
		as.add(new Stock("MUNJALAU" , "883"));
		as.add(new Stock("MUNJALSHOW" , "884"));
		as.add(new Stock("MURUDCERA" , "885"));
		as.add(new Stock("MUTHOOTCAP" , "886"));
		as.add(new Stock("MUTHOOTFIN" , "887"));
		as.add(new Stock("MVL" , "888"));
		as.add(new Stock("MYSOREBANK" , "889"));
		as.add(new Stock("N100" , "890"));
		as.add(new Stock("NAGAROIL" , "891"));
		as.add(new Stock("NAGREEKCAP" , "892"));
		as.add(new Stock("NAGREEKEXP" , "893"));
		as.add(new Stock("NAHARCAP" , "894"));
		as.add(new Stock("NAHARINDUS" , "895"));
		as.add(new Stock("NAHARPOLY" , "896"));
		as.add(new Stock("NAHARSPING" , "897"));
		as.add(new Stock("NAKODA" , "898"));
		as.add(new Stock("NATCOPHARM" , "899"));
		as.add(new Stock("NATHBIOGEN" , "900"));
		as.add(new Stock("NATIONALUM" , "901"));
		as.add(new Stock("NAUKRI" , "902"));
		as.add(new Stock("NAVINFLUOR" , "903"));
		as.add(new Stock("NAVKARCORP" , "904"));
		as.add(new Stock("NAVNETEDUL" , "905"));
		as.add(new Stock("NBCC" , "906"));
		as.add(new Stock("NBVENTURES" , "907"));
		as.add(new Stock("NCC" , "908"));
		as.add(new Stock("NCLIND" , "909"));
		as.add(new Stock("NDL" , "910"));
		as.add(new Stock("NDTV" , "911"));
		as.add(new Stock("NECCLTD" , "912"));
		as.add(new Stock("NECLIFE" , "913"));
		as.add(new Stock("NELCAST" , "914"));
		as.add(new Stock("NELCO" , "915"));
		as.add(new Stock("NESCO" , "916"));
		as.add(new Stock("NESTLEIND" , "917"));
		as.add(new Stock("NET4" , "918"));
		as.add(new Stock("NETWORK18" , "919"));
		as.add(new Stock("NEULANDLAB" , "920"));
		as.add(new Stock("NEXTMEDIA" , "921"));
		as.add(new Stock("NEYVELILIG" , "922"));
		as.add(new Stock("NFL" , "923"));
		as.add(new Stock("NH" , "924"));
		as.add(new Stock("NHPC" , "925"));
		as.add(new Stock("NIBL" , "926"));
		as.add(new Stock("NIF100IWIN" , "927"));
		as.add(new Stock("NIFTYBEES" , "928"));
		as.add(new Stock("NIFTYEES" , "929"));
		as.add(new Stock("NIFTYIWIN" , "930"));
		as.add(new Stock("NIITLTD" , "931"));
		as.add(new Stock("NIITTECH" , "932"));
		as.add(new Stock("NILAINFRA" , "933"));
		as.add(new Stock("NILKAMAL" , "934"));
		as.add(new Stock("NIPPOBATRY" , "935"));
		as.add(new Stock("NIRVIKARA" , "936"));
		as.add(new Stock("NITCO" , "937"));
		as.add(new Stock("NITESHEST" , "938"));
		as.add(new Stock("NITINFIRE" , "939"));
		as.add(new Stock("NITINSPIN" , "940"));
		as.add(new Stock("NKIND" , "941"));
		as.add(new Stock("NMDC" , "942"));
		as.add(new Stock("NOCIL" , "943"));
		as.add(new Stock("NOIDATOLL" , "944"));
		as.add(new Stock("NRBBEARING" , "945"));
		as.add(new Stock("NSIL" , "946"));
		as.add(new Stock("NTPC" , "947"));
		as.add(new Stock("NUCLEUS" , "948"));
		as.add(new Stock("NUTEK" , "949"));
		as.add(new Stock("OBEROIRLTY" , "950"));
		as.add(new Stock("OCCL" , "951"));
		as.add(new Stock("OCL" , "952"));
		as.add(new Stock("OFSS" , "953"));
		as.add(new Stock("OIL" , "954"));
		as.add(new Stock("OILCOUNTUB" , "955"));
		as.add(new Stock("OISL" , "956"));
		as.add(new Stock("OMAXAUTO" , "957"));
		as.add(new Stock("OMAXE" , "958"));
		as.add(new Stock("OMKARCHEM" , "959"));
		as.add(new Stock("OMMETALS" , "960"));
		as.add(new Stock("OMNITECH" , "961"));
		as.add(new Stock("ONELIFECAP" , "962"));
		as.add(new Stock("ONGC" , "963"));
		as.add(new Stock("ONMOBILE" , "964"));
		as.add(new Stock("ONWARDTEC" , "965"));
		as.add(new Stock("OPTOCIRCUI" , "966"));
		as.add(new Stock("ORBITCORP" , "967"));
		as.add(new Stock("ORBTEXP" , "968"));
		as.add(new Stock("ORCHIDPHAR" , "969"));
		as.add(new Stock("ORICONENT" , "970"));
		as.add(new Stock("ORIENTABRA" , "971"));
		as.add(new Stock("ORIENTALTL" , "972"));
		as.add(new Stock("ORIENTBANK" , "973"));
		as.add(new Stock("ORIENTBELL" , "974"));
		as.add(new Stock("ORIENTCEM" , "975"));
		as.add(new Stock("ORIENTHOT" , "976"));
		as.add(new Stock("ORIENTLTD" , "977"));
		as.add(new Stock("ORIENTPPR" , "978"));
		as.add(new Stock("ORIENTREF" , "979"));
		as.add(new Stock("ORISSAMINE" , "980"));
		as.add(new Stock("ORTEL" , "981"));
		as.add(new Stock("ORTINLABSS" , "982"));
		as.add(new Stock("OUDHSUG" , "983"));
		as.add(new Stock("PAEL" , "984"));
		as.add(new Stock("PAGEIND" , "985"));
		as.add(new Stock("PALREDTEC" , "986"));
		as.add(new Stock("PANACEABIO" , "987"));
		as.add(new Stock("PANAMAPET" , "988"));
		as.add(new Stock("PANORAMUNI" , "989"));
		as.add(new Stock("PAPERPROD" , "990"));
		as.add(new Stock("PARABDRUGS" , "991"));
		as.add(new Stock("PARACABLES" , "992"));
		as.add(new Stock("PARAGMILK" , "993"));
		as.add(new Stock("PARRYSUGAR" , "994"));
		as.add(new Stock("PARSVNATH" , "995"));
		as.add(new Stock("PATELENG" , "996"));
		as.add(new Stock("PATINTLOG" , "997"));
		as.add(new Stock("PATSPINLTD" , "998"));
		as.add(new Stock("PBAINFRA" , "999"));
		as.add(new Stock("PCJEWELLER" , "1000"));
		as.add(new Stock("PDPL" , "1001"));
		as.add(new Stock("PDSMFL" , "1002"));
		as.add(new Stock("PDUMJEIND" , "1003"));
		as.add(new Stock("PDUMJEPULP" , "1004"));
		as.add(new Stock("PEARLPOLY" , "1005"));
		as.add(new Stock("PEL" , "1006"));
		as.add(new Stock("PENIND" , "1007"));
		as.add(new Stock("PENINLAND" , "1008"));
		as.add(new Stock("PENPEBS" , "1009"));
		as.add(new Stock("PERSISTENT" , "1010"));
		as.add(new Stock("PETRONENGG" , "1011"));
		as.add(new Stock("PETRONET" , "1012"));
		as.add(new Stock("PFC" , "1013"));
		as.add(new Stock("PFIZER" , "1014"));
		as.add(new Stock("PFOCUS" , "1015"));
		as.add(new Stock("PFS" , "1016"));
		as.add(new Stock("PGEL" , "1017"));
		as.add(new Stock("PGHH" , "1018"));
		as.add(new Stock("PGIL" , "1019"));
		as.add(new Stock("PHILIPCARB" , "1020"));
		as.add(new Stock("PHOENIXLL" , "1021"));
		as.add(new Stock("PHOENIXLTD" , "1022"));
		as.add(new Stock("PIDILITIND" , "1023"));
		as.add(new Stock("PIIND" , "1024"));
		as.add(new Stock("PILITA" , "1025"));
		as.add(new Stock("PINCON" , "1026"));
		as.add(new Stock("PIONDIST" , "1027"));
		as.add(new Stock("PIONEEREMB" , "1028"));
		as.add(new Stock("PIRPHYTO" , "1029"));
		as.add(new Stock("PITTILAM" , "1030"));
		as.add(new Stock("PKTEA" , "1031"));
		as.add(new Stock("PLASTIBLEN" , "1032"));
		as.add(new Stock("PNB" , "1033"));
		as.add(new Stock("PNBGILTS" , "1034"));
		as.add(new Stock("PNC" , "1035"));
		as.add(new Stock("PNCINFRA" , "1036"));
		as.add(new Stock("PNEUMATIC" , "1037"));
		as.add(new Stock("POCHIRAJU" , "1038"));
		as.add(new Stock("POKARNA" , "1039"));
		as.add(new Stock("POLARIS" , "1040"));
		as.add(new Stock("POLYMED" , "1041"));
		as.add(new Stock("POLYPLEX" , "1042"));
		as.add(new Stock("PONNIERODE" , "1043"));
		as.add(new Stock("POWERGRID" , "1044"));
		as.add(new Stock("POWERMECH" , "1045"));
		as.add(new Stock("PPAP" , "1046"));
		as.add(new Stock("PRABHAT" , "1047"));
		as.add(new Stock("PRAENG" , "1048"));
		as.add(new Stock("PRAJIND" , "1049"));
		as.add(new Stock("PRAKASH" , "1050"));
		as.add(new Stock("PRAKASHCON" , "1051"));
		as.add(new Stock("PRAKASHSTL" , "1052"));
		as.add(new Stock("PRATIBHA" , "1053"));
		as.add(new Stock("PRECAM" , "1054"));
		as.add(new Stock("PRECOT" , "1055"));
		as.add(new Stock("PRECWIRE" , "1056"));
		as.add(new Stock("PREMEXPLN" , "1057"));
		as.add(new Stock("PREMIER" , "1058"));
		as.add(new Stock("PRESSMN" , "1059"));
		as.add(new Stock("PRESTIGE" , "1060"));
		as.add(new Stock("PRICOL" , "1061"));
		as.add(new Stock("PRIMESECU" , "1062"));
		as.add(new Stock("PRISMCEM" , "1063"));
		as.add(new Stock("PROVOGE" , "1064"));
		as.add(new Stock("PROZONINTU" , "1065"));
		as.add(new Stock("PSB" , "1066"));
		as.add(new Stock("PSL" , "1067"));
		as.add(new Stock("PSUBNKBEES" , "1068"));
		as.add(new Stock("PTC" , "1069"));
		as.add(new Stock("PTL" , "1070"));
		as.add(new Stock("PUNJABCHEM" , "1071"));
		as.add(new Stock("PUNJLLOYD" , "1072"));
		as.add(new Stock("PURVA" , "1073"));
		as.add(new Stock("PVP" , "1074"));
		as.add(new Stock("PVR" , "1075"));
		as.add(new Stock("QGOLDHALF" , "1076"));
		as.add(new Stock("QNIFTY" , "1077"));
		as.add(new Stock("QUESS" , "1078"));
		as.add(new Stock("QUICKHEAL" , "1079"));
		as.add(new Stock("RADAAN" , "1080"));
		as.add(new Stock("RADICO" , "1081"));
		as.add(new Stock("RAIN" , "1082"));
		as.add(new Stock("RAINBOWPAP" , "1083"));
		as.add(new Stock("RAIREKMOH" , "1084"));
		as.add(new Stock("RAJESHEXPO" , "1085"));
		as.add(new Stock("RAJOIL" , "1086"));
		as.add(new Stock("RAJRAYON" , "1087"));
		as.add(new Stock("RAJSREESUG" , "1088"));
		as.add(new Stock("RAJTV" , "1089"));
		as.add(new Stock("RALLIS" , "1090"));
		as.add(new Stock("RAMANEWS" , "1091"));
		as.add(new Stock("RAMASTEEL" , "1092"));
		as.add(new Stock("RAMCOCEM" , "1093"));
		as.add(new Stock("RAMCOIND" , "1094"));
		as.add(new Stock("RAMCOSYS" , "1095"));
		as.add(new Stock("RAMKY" , "1096"));
		as.add(new Stock("RANASUG" , "1097"));
		as.add(new Stock("RANEENGINE" , "1098"));
		as.add(new Stock("RANEHOLDIN" , "1099"));
		as.add(new Stock("RASOYPR" , "1100"));
		as.add(new Stock("RATNAMANI" , "1101"));
		as.add(new Stock("RAYMOND" , "1102"));
		as.add(new Stock("RBL" , "1103"));
		as.add(new Stock("RCF" , "1104"));
		as.add(new Stock("RCOM" , "1105"));
		as.add(new Stock("RDEL" , "1106"));
		as.add(new Stock("RECLTD" , "1107"));
		as.add(new Stock("REDINGTON" , "1108"));
		as.add(new Stock("REFEX" , "1109"));
		as.add(new Stock("REIAGROLTD" , "1110"));
		as.add(new Stock("REISIXTEN" , "1111"));
		as.add(new Stock("RELAXO" , "1112"));
		as.add(new Stock("RELBANK" , "1113"));
		as.add(new Stock("RELCAPITAL" , "1114"));
		as.add(new Stock("RELCNX100" , "1115"));
		as.add(new Stock("RELCONS" , "1116"));
		as.add(new Stock("RELDIVOPP" , "1117"));
		as.add(new Stock("RELGOLD" , "1118"));
		as.add(new Stock("RELIANCE" , "1119"));
		as.add(new Stock("RELIGARE" , "1120"));
		as.add(new Stock("RELINFRA" , "1121"));
		as.add(new Stock("RELNIFTY" , "1122"));
		as.add(new Stock("REMSONSIND" , "1123"));
		as.add(new Stock("RENUKA" , "1124"));
		as.add(new Stock("REPCOHOME" , "1125"));
		as.add(new Stock("REPRO" , "1126"));
		as.add(new Stock("RESPONIND" , "1127"));
		as.add(new Stock("REVATHI" , "1128"));
		as.add(new Stock("RICOAUTO" , "1129"));
		as.add(new Stock("RIIL" , "1130"));
		as.add(new Stock("RJL" , "1131"));
		as.add(new Stock("RKDL" , "1132"));
		as.add(new Stock("RKFORGE" , "1133"));
		as.add(new Stock("RMCL" , "1134"));
		as.add(new Stock("RML" , "1135"));
		as.add(new Stock("ROHITFERRO" , "1136"));
		as.add(new Stock("ROHLTD" , "1137"));
		as.add(new Stock("ROLTA" , "1138"));
		as.add(new Stock("ROSSELLIND" , "1139"));
		as.add(new Stock("RPGLIFE" , "1140"));
		as.add(new Stock("RPOWER" , "1141"));
		as.add(new Stock("RPPINFRA" , "1142"));
		as.add(new Stock("RSSOFTWARE" , "1143"));
		as.add(new Stock("RSWM" , "1144"));
		as.add(new Stock("RSYSTEMS" , "1145"));
		as.add(new Stock("RTNINFRA" , "1146"));
		as.add(new Stock("RTNPOWER" , "1147"));
		as.add(new Stock("RUBYMILLS" , "1148"));
		as.add(new Stock("RUCHIRA" , "1149"));
		as.add(new Stock("RUCHISOYA" , "1150"));
		as.add(new Stock("RUPA" , "1151"));
		as.add(new Stock("RUSHIL" , "1152"));
		as.add(new Stock("SABTN" , "1153"));
		as.add(new Stock("SADBHAV" , "1154"));
		as.add(new Stock("SADBHIN" , "1155"));
		as.add(new Stock("SAGCEM" , "1156"));
		as.add(new Stock("SAIL" , "1157"));
		as.add(new Stock("SAKHTISUG" , "1158"));
		as.add(new Stock("SAKSOFT" , "1159"));
		as.add(new Stock("SAKUMA" , "1160"));
		as.add(new Stock("SALONA" , "1161"));
		as.add(new Stock("SALORAINTL" , "1162"));
		as.add(new Stock("SALSTEEL" , "1163"));
		as.add(new Stock("SALZERELEC" , "1164"));
		as.add(new Stock("SAMBHAAV" , "1165"));
		as.add(new Stock("SANDESH" , "1166"));
		as.add(new Stock("SANGAMIND" , "1167"));
		as.add(new Stock("SANGHIIND" , "1168"));
		as.add(new Stock("SANGHVIFOR" , "1169"));
		as.add(new Stock("SANGHVIMOV" , "1170"));
		as.add(new Stock("SANOFI" , "1171"));
		as.add(new Stock("SANWARIA" , "1172"));
		as.add(new Stock("SARDAEN" , "1173"));
		as.add(new Stock("SAREGAMA" , "1174"));
		as.add(new Stock("SARLAPOLY" , "1175"));
		as.add(new Stock("SASKEN" , "1176"));
		as.add(new Stock("SATHAISPAT" , "1177"));
		as.add(new Stock("SATIN" , "1178"));
		as.add(new Stock("SBBJ" , "1179"));
		as.add(new Stock("SBIN" , "1180"));
		as.add(new Stock("SBT" , "1181"));
		as.add(new Stock("SCHNEIDER" , "1182"));
		as.add(new Stock("SCI" , "1183"));
		as.add(new Stock("SDBL" , "1184"));
		as.add(new Stock("SEAMECLTD" , "1185"));
		as.add(new Stock("SEINV" , "1186"));
		as.add(new Stock("SELAN" , "1187"));
		as.add(new Stock("SELMCL" , "1188"));
		as.add(new Stock("SENSEXIWIN" , "1189"));
		as.add(new Stock("SEPOWER" , "1190"));
		as.add(new Stock("SEQUENT" , "1191"));
		as.add(new Stock("SERVALL" , "1192"));
		as.add(new Stock("SESHAPAPER" , "1193"));
		as.add(new Stock("SETCO" , "1194"));
		as.add(new Stock("SETF10GILT" , "1195"));
		as.add(new Stock("SETFGOLD" , "1196"));
		as.add(new Stock("SETFNIF50" , "1197"));
		as.add(new Stock("SETFNIFBK" , "1198"));
		as.add(new Stock("SETFNN50" , "1199"));
		as.add(new Stock("SFCL" , "1200"));
		as.add(new Stock("SGJHL" , "1201"));
		as.add(new Stock("SGL" , "1202"));
		as.add(new Stock("SHAHALLOYS" , "1203"));
		as.add(new Stock("SHAKTIPUMP" , "1204"));
		as.add(new Stock("SHALPAINTS" , "1205"));
		as.add(new Stock("SHANTIGEAR" , "1206"));
		as.add(new Stock("SHARDACROP" , "1207"));
		as.add(new Stock("SHARDAMOTR" , "1208"));
		as.add(new Stock("SHARIABEES" , "1209"));
		as.add(new Stock("SHARONBIO" , "1210"));
		as.add(new Stock("SHEMAROO" , "1211"));
		as.add(new Stock("SHILPAMED" , "1212"));
		as.add(new Stock("SHILPI" , "1213"));
		as.add(new Stock("SHIRPUR-G" , "1214"));
		as.add(new Stock("SHIVAMAUTO" , "1215"));
		as.add(new Stock("SHIVTEX" , "1216"));
		as.add(new Stock("SHK" , "1217"));
		as.add(new Stock("SHOPERSTOP" , "1218"));
		as.add(new Stock("SHREECEM" , "1219"));
		as.add(new Stock("SHREEPUSHK" , "1220"));
		as.add(new Stock("SHREERAMA" , "1221"));
		as.add(new Stock("SHREYANIND" , "1222"));
		as.add(new Stock("SHREYAS" , "1223"));
		as.add(new Stock("SHRIRAMCIT" , "1224"));
		as.add(new Stock("SHRIRAMEPC" , "1225"));
		as.add(new Stock("SHYAMCENT" , "1226"));
		as.add(new Stock("SHYAMTEL" , "1227"));
		as.add(new Stock("SICAGEN" , "1228"));
		as.add(new Stock("SICAL" , "1229"));
		as.add(new Stock("SIEMENS" , "1230"));
		as.add(new Stock("SIGNET" , "1231"));
		as.add(new Stock("SILINV" , "1232"));
		as.add(new Stock("SIMBHALS" , "1233"));
		as.add(new Stock("SIMPLEX" , "1234"));
		as.add(new Stock("SIMPLEXINF" , "1235"));
		as.add(new Stock("SINTEX" , "1236"));
		as.add(new Stock("SITASHREE" , "1237"));
		as.add(new Stock("SITICABLE" , "1238"));
		as.add(new Stock("SIYSIL" , "1239"));
		as.add(new Stock("SJVN" , "1240"));
		as.add(new Stock("SKFINDIA" , "1241"));
		as.add(new Stock("SKIL" , "1242"));
		as.add(new Stock("SKIPPER" , "1243"));
		as.add(new Stock("SKMEGGPROD" , "1244"));
		as.add(new Stock("SMARTLINK" , "1245"));
		as.add(new Stock("SMLISUZU" , "1246"));
		as.add(new Stock("SMPL" , "1247"));
		as.add(new Stock("SMSPHARMA" , "1248"));
		as.add(new Stock("SNOWMAN" , "1249"));
		as.add(new Stock("SOBHA" , "1250"));
		as.add(new Stock("SOLARINDS" , "1251"));
		as.add(new Stock("SOMANYCERA" , "1252"));
		as.add(new Stock("SOMATEX" , "1253"));
		as.add(new Stock("SOMICONVEY" , "1254"));
		as.add(new Stock("SONASTEER" , "1255"));
		as.add(new Stock("SONATSOFTW" , "1256"));
		as.add(new Stock("SOTL" , "1257"));
		as.add(new Stock("SOUTHBANK" , "1258"));
		as.add(new Stock("SPARC" , "1259"));
		as.add(new Stock("SPECIALITY" , "1260"));
		as.add(new Stock("SPENTEX" , "1261"));
		as.add(new Stock("SPHEREGSL" , "1262"));
		as.add(new Stock("SPIC" , "1263"));
		as.add(new Stock("SPICEMOBI" , "1264"));
		as.add(new Stock("SPLIL" , "1265"));
		as.add(new Stock("SPMLINFRA" , "1266"));
		as.add(new Stock("SPYL" , "1267"));
		as.add(new Stock("SQSBFSI" , "1268"));
		as.add(new Stock("SREEL" , "1269"));
		as.add(new Stock("SREINFRA" , "1270"));
		as.add(new Stock("SRF" , "1271"));
		as.add(new Stock("SRHHYPOLTD" , "1272"));
		as.add(new Stock("SRIPIPES" , "1273"));
		as.add(new Stock("SRSLTD" , "1274"));
		as.add(new Stock("SRTRANSFIN" , "1275"));
		as.add(new Stock("SSWL" , "1276"));
		as.add(new Stock("STAMPEDE" , "1277"));
		as.add(new Stock("STAR" , "1278"));
		as.add(new Stock("STARPAPER" , "1279"));
		as.add(new Stock("STCINDIA" , "1280"));
		as.add(new Stock("STEL" , "1281"));
		as.add(new Stock("STERLINBIO" , "1282"));
		as.add(new Stock("STERTOOLS" , "1283"));
		as.add(new Stock("STINDIA" , "1284"));
		as.add(new Stock("STOREONE" , "1285"));
		as.add(new Stock("STRTECH" , "1286"));
		as.add(new Stock("SUBEX" , "1287"));
		as.add(new Stock("SUBROS" , "1288"));
		as.add(new Stock("SUDAR" , "1289"));
		as.add(new Stock("SUDARSCHEM" , "1290"));
		as.add(new Stock("SUJANATWR" , "1291"));
		as.add(new Stock("SUJANAUNI" , "1292"));
		as.add(new Stock("SUMEETINDS" , "1293"));
		as.add(new Stock("SUMMITSEC" , "1294"));
		as.add(new Stock("SUNCLAYLTD" , "1295"));
		as.add(new Stock("SUNDARAM" , "1296"));
		as.add(new Stock("SUNDARMFIN" , "1297"));
		as.add(new Stock("SUNDRMBRAK" , "1298"));
		as.add(new Stock("SUNDRMFAST" , "1299"));
		as.add(new Stock("SUNFLAG" , "1300"));
		as.add(new Stock("SUNILHITEC" , "1301"));
		as.add(new Stock("SUNPHARMA" , "1302"));
		as.add(new Stock("SUNTECK" , "1303"));
		as.add(new Stock("SUNTV" , "1304"));
		as.add(new Stock("SUPERHOUSE" , "1305"));
		as.add(new Stock("SUPERSPIN" , "1306"));
		as.add(new Stock("SUPPETRO" , "1307"));
		as.add(new Stock("SUPRAJIT" , "1308"));
		as.add(new Stock("SUPREMEIND" , "1309"));
		as.add(new Stock("SUPREMEINF" , "1310"));
		as.add(new Stock("SURANAIND" , "1311"));
		as.add(new Stock("SURANASOL" , "1312"));
		as.add(new Stock("SURANAT&P" , "1313"));
		as.add(new Stock("SURYALAXMI" , "1314"));
		as.add(new Stock("SURYAROSNI" , "1315"));
		as.add(new Stock("SUTLEJTEX" , "1316"));
		as.add(new Stock("SUVEN" , "1317"));
		as.add(new Stock("SUZLON" , "1318"));
		as.add(new Stock("SWANENERGY" , "1319"));
		as.add(new Stock("SWARAJENG" , "1320"));
		as.add(new Stock("SWELECTES" , "1321"));
		as.add(new Stock("SYMPHONY" , "1322"));
		as.add(new Stock("SYNCOM" , "1323"));
		as.add(new Stock("SYNDIBANK" , "1324"));
		as.add(new Stock("SYNGENE" , "1325"));
		as.add(new Stock("TAINWALCHM" , "1326"));
		as.add(new Stock("TAJGVK" , "1327"));
		as.add(new Stock("TAKE" , "1328"));
		as.add(new Stock("TALBROAUTO" , "1329"));
		as.add(new Stock("TALWALKARS" , "1330"));
		as.add(new Stock("TANLA" , "1331"));
		as.add(new Stock("TANTIACONS" , "1332"));
		as.add(new Stock("TARAJEWELS" , "1333"));
		as.add(new Stock("TARAPUR" , "1334"));
		as.add(new Stock("TARMAT" , "1335"));
		as.add(new Stock("TATACHEM" , "1336"));
		as.add(new Stock("TATACOFFEE" , "1337"));
		as.add(new Stock("TATACOMM" , "1338"));
		as.add(new Stock("TATAELXSI" , "1339"));
		as.add(new Stock("TATAGLOBAL" , "1340"));
		as.add(new Stock("TATAINVEST" , "1341"));
		as.add(new Stock("TATAMETALI" , "1342"));
		as.add(new Stock("TATAMOTORS" , "1343"));
		as.add(new Stock("TATAMTRDVR" , "1344"));
		as.add(new Stock("TATAPOWER" , "1345"));
		as.add(new Stock("TATASPONGE" , "1346"));
		as.add(new Stock("TATASTEEL" , "1347"));
		as.add(new Stock("TBZ" , "1348"));
		as.add(new Stock("TCI" , "1349"));
		as.add(new Stock("TCIDEVELOP" , "1350"));
		as.add(new Stock("TCIFINANCE" , "1351"));
		as.add(new Stock("TCS" , "1352"));
		as.add(new Stock("TDPOWERSYS" , "1353"));
		as.add(new Stock("TEAMLEASE" , "1354"));
		as.add(new Stock("TECHM" , "1355"));
		as.add(new Stock("TECHNO" , "1356"));
		as.add(new Stock("TECHNOFAB" , "1357"));
		as.add(new Stock("TEXINFRA" , "1358"));
		as.add(new Stock("TEXMOPIPES" , "1359"));
		as.add(new Stock("TEXRAIL" , "1360"));
		as.add(new Stock("TFCILTD" , "1361"));
		as.add(new Stock("TFL" , "1362"));
		as.add(new Stock("TGBHOTELS" , "1363"));
		as.add(new Stock("THANGAMAYL" , "1364"));
		as.add(new Stock("THEMISMED" , "1365"));
		as.add(new Stock("THERMAX" , "1366"));
		as.add(new Stock("THIRUSUGAR" , "1367"));
		as.add(new Stock("THOMASCOOK" , "1368"));
		as.add(new Stock("THYROCARE" , "1369"));
		as.add(new Stock("TI" , "1370"));
		as.add(new Stock("TIDEWATER" , "1371"));
		as.add(new Stock("TIIL" , "1372"));
		as.add(new Stock("TIJARIA" , "1373"));
		as.add(new Stock("TIL" , "1374"));
		as.add(new Stock("TIMESGTY" , "1375"));
		as.add(new Stock("TIMETECHNO" , "1376"));
		as.add(new Stock("TIMKEN" , "1377"));
		as.add(new Stock("TINPLATE" , "1378"));
		as.add(new Stock("TIPSINDLTD" , "1379"));
		as.add(new Stock("TIRUMALCHM" , "1380"));
		as.add(new Stock("TITAN" , "1381"));
		as.add(new Stock("TNPETRO" , "1382"));
		as.add(new Stock("TNPL" , "1383"));
		as.add(new Stock("TODAYS" , "1384"));
		as.add(new Stock("TOKYOPLAST" , "1385"));
		as.add(new Stock("TORNTPHARM" , "1386"));
		as.add(new Stock("TORNTPOWER" , "1387"));
		as.add(new Stock("TPLPLASTEH" , "1388"));
		as.add(new Stock("TREEHOUSE" , "1389"));
		as.add(new Stock("TRENT" , "1390"));
		as.add(new Stock("TRF" , "1391"));
		as.add(new Stock("TRIDENT" , "1392"));
		as.add(new Stock("TRIGYN" , "1393"));
		as.add(new Stock("TRIL" , "1394"));
		as.add(new Stock("TRITURBINE" , "1395"));
		as.add(new Stock("TRIVENI" , "1396"));
		as.add(new Stock("TTKHLTCARE" , "1397"));
		as.add(new Stock("TTKPRESTIG" , "1398"));
		as.add(new Stock("TTL" , "1399"));
		as.add(new Stock("TTML" , "1400"));
		as.add(new Stock("TUBEINVEST" , "1401"));
		as.add(new Stock("TULSI" , "1402"));
		as.add(new Stock("TV18BRDCST" , "1403"));
		as.add(new Stock("TVSELECT" , "1404"));
		as.add(new Stock("TVSMOTOR" , "1405"));
		as.add(new Stock("TVSSRICHAK" , "1406"));
		as.add(new Stock("TVTODAY" , "1407"));
		as.add(new Stock("TWL" , "1408"));
		as.add(new Stock("UBHOLDINGS" , "1409"));
		as.add(new Stock("UBL" , "1410"));
		as.add(new Stock("UCALFUEL" , "1411"));
		as.add(new Stock("UCOBANK" , "1412"));
		as.add(new Stock("UFLEX" , "1413"));
		as.add(new Stock("UFO" , "1414"));
		as.add(new Stock("UGARSUGAR" , "1415"));
		as.add(new Stock("UJAAS" , "1416"));
		as.add(new Stock("UJJIVAN" , "1417"));
		as.add(new Stock("ULTRACEMCO" , "1418"));
		as.add(new Stock("UMANGDAIRY" , "1419"));
		as.add(new Stock("UMESLTD" , "1420"));
		as.add(new Stock("UNICHEMLAB" , "1421"));
		as.add(new Stock("UNIENTER" , "1422"));
		as.add(new Stock("UNIONBANK" , "1423"));
		as.add(new Stock("UNIPLY" , "1424"));
		as.add(new Stock("UNITECH" , "1425"));
		as.add(new Stock("UNITEDBNK" , "1426"));
		as.add(new Stock("UNITEDTEA" , "1427"));
		as.add(new Stock("UNITY" , "1428"));
		as.add(new Stock("UNIVCABLES" , "1429"));
		as.add(new Stock("UPERGANGES" , "1430"));
		as.add(new Stock("UPL" , "1431"));
		as.add(new Stock("USHAMART" , "1432"));
		as.add(new Stock("USHERAGRO" , "1433"));
		as.add(new Stock("UTINIFTETF" , "1434"));
		as.add(new Stock("UTISENSETF" , "1435"));
		as.add(new Stock("UTTAMSTL" , "1436"));
		as.add(new Stock("UTTAMSUGAR" , "1437"));
		as.add(new Stock("UVSL" , "1438"));
		as.add(new Stock("V2RETAIL" , "1439"));
		as.add(new Stock("VADILALIND" , "1440"));
		as.add(new Stock("VAIBHAVGBL" , "1441"));
		as.add(new Stock("VAKRANGEE" , "1442"));
		as.add(new Stock("VALECHAENG" , "1443"));
		as.add(new Stock("VALUEIND" , "1444"));
		as.add(new Stock("VARDHACRLC" , "1445"));
		as.add(new Stock("VARDMNPOLY" , "1446"));
		as.add(new Stock("VASCONEQ" , "1447"));
		as.add(new Stock("VASWANI" , "1448"));
		as.add(new Stock("VEDL" , "1449"));
		as.add(new Stock("VENKEYS" , "1450"));
		as.add(new Stock("VENUSREM" , "1451"));
		as.add(new Stock("VESUVIUS" , "1452"));
		as.add(new Stock("VETO" , "1453"));
		as.add(new Stock("VGUARD" , "1454"));
		as.add(new Stock("VHL" , "1455"));
		as.add(new Stock("VICEROY" , "1456"));
		as.add(new Stock("VIDEOIND" , "1457"));
		as.add(new Stock("VIDHIDYE" , "1458"));
		as.add(new Stock("VIJAYABANK" , "1459"));
		as.add(new Stock("VIJIFIN" , "1460"));
		as.add(new Stock("VIJSHAN" , "1461"));
		as.add(new Stock("VIKASECO" , "1462"));
		as.add(new Stock("VIMALOIL" , "1463"));
		as.add(new Stock("VIMTALABS" , "1464"));
		as.add(new Stock("VINATIORGA" , "1465"));
		as.add(new Stock("VINDHYATEL" , "1466"));
		as.add(new Stock("VINYLINDIA" , "1467"));
		as.add(new Stock("VIPIND" , "1468"));
		as.add(new Stock("VIPULLTD" , "1469"));
		as.add(new Stock("VISAKAIND" , "1470"));
		as.add(new Stock("VISASTEEL" , "1471"));
		as.add(new Stock("VISESHINFO" , "1472"));
		as.add(new Stock("VISHNU" , "1473"));
		as.add(new Stock("VISUINTL" , "1474"));
		as.add(new Stock("VIVIDHA" , "1475"));
		as.add(new Stock("VIVIMEDLAB" , "1476"));
		as.add(new Stock("VKSPL" , "1477"));
		as.add(new Stock("VLSFINANCE" , "1478"));
		as.add(new Stock("VMART" , "1479"));
		as.add(new Stock("VOLTAMP" , "1480"));
		as.add(new Stock("VOLTAS" , "1481"));
		as.add(new Stock("VRLLOG" , "1482"));
		as.add(new Stock("VSSL" , "1483"));
		as.add(new Stock("VSTIND" , "1484"));
		as.add(new Stock("VSTTILLERS" , "1485"));
		as.add(new Stock("VTL" , "1486"));
		as.add(new Stock("WABAG" , "1487"));
		as.add(new Stock("WABCOINDIA" , "1488"));
		as.add(new Stock("WALCHANNAG" , "1489"));
		as.add(new Stock("WEBELSOLAR" , "1490"));
		as.add(new Stock("WEIZFOREX" , "1491"));
		as.add(new Stock("WEIZMANIND" , "1492"));
		as.add(new Stock("WELCORP" , "1493"));
		as.add(new Stock("WELENT" , "1494"));
		as.add(new Stock("WELINV" , "1495"));
		as.add(new Stock("WELSPUNIND" , "1496"));
		as.add(new Stock("WENDT" , "1497"));
		as.add(new Stock("WHEELS" , "1498"));
		as.add(new Stock("WHIRLPOOL" , "1499"));
		as.add(new Stock("WILLAMAGOR" , "1500"));
		as.add(new Stock("WINDMACHIN" , "1501"));
		as.add(new Stock("WINSOME" , "1502"));
		as.add(new Stock("WIPRO" , "1503"));
		as.add(new Stock("WOCKPHARMA" , "1504"));
		as.add(new Stock("WONDERLA" , "1505"));
		as.add(new Stock("WSI" , "1506"));
		as.add(new Stock("WSTCSTPAPR" , "1507"));
		as.add(new Stock("XCHANGING" , "1508"));
		as.add(new Stock("XLENERGY" , "1509"));
		as.add(new Stock("XPROINDIA" , "1510"));
		as.add(new Stock("YESBANK" , "1511"));
		as.add(new Stock("ZANDUREALT" , "1512"));
		as.add(new Stock("ZEEL" , "1513"));
		as.add(new Stock("ZEELEARN" , "1514"));
		as.add(new Stock("ZEEMEDIA" , "1515"));
		as.add(new Stock("ZENITHBIR" , "1516"));
		as.add(new Stock("ZENSARTECH" , "1517"));
		as.add(new Stock("ZENTEC" , "1518"));
		as.add(new Stock("ZICOM" , "1519"));
		as.add(new Stock("ZODIACLOTH" , "1520"));
		as.add(new Stock("ZUARI" , "1521"));
		as.add(new Stock("ZUARIGLOB" , "1522"));
		as.add(new Stock("ZYDUSWELL" , "1523"));
		
		return as;
	}
}// END of class
